FROM python:3.10

RUN apt-get update && apt-get install -y python3-pip
RUN apt-get -y install libgl1-mesa-glx

RUN pip install --upgrade pip

COPY requirements.txt ./requirements.txt 

RUN pip install -r requirements.txt 

COPY . /brush-buddy
EXPOSE 8000

RUN mkdir -p ./assets
CMD [ "python", "/brush-buddy/main.py", "--host", "0.0.0.0", "--port", "8000"]